### ISSUE TITLE
Feature Request: Hide Watermark

### ISSUE THREAD

**Issue by brian6932** [ioriayane/Hagoromo#111]
An option to toggle the watermark in the bottom right, imo should be hidden by default.

**Comment by ioriayane** [comment]
Thanks for your request.
Do you have a problem with the watermark overlapping the rightmost column making the post difficult to read?

<img width="370" alt="スクリーンショット 2023-12-25 193810" src="https://github.com/ioriayane/Hagoromo/assets/5165379/4dc18c00-b067-4980-8764-f6178d46513d">

**Comment by brian6932** [comment]
Not a large issue, but I think it'd be nice to be able to toggle it off 🤷. All the information is in the about page anyway.

**Comment by ioriayane** [comment]
Please wait for the next release.
